import { ChatRoom, Message, User } from '../utils/type';
import { newGuid } from '../utils/helper';
import { addHours, addMinutes, NOW, SYSTEM_NOW, toSystemDate } from './dateHelper';
import IMG_LIKE from '../resources/like.png';
import IMG_HAHA from '../resources/haha.png';
import IMG_HEART from '../resources/heart.png';
import IMG_WOW from '../resources/wow.png';
import IMG_SAD from '../resources/sad.png';
import IMG_ANGRY from '../resources/angry.png';
const USERS: User[] = [
	{
		id: newGuid(),
		userName: 'Spider man',
		gender: 'Male',
		imageSrc: 'Spiderman.jpg',
	},
	{
		id: newGuid(),
		userName: 'Iron man',
		gender: 'Male',
		imageSrc: 'Ironman.jpg',
	},
	{
		id: newGuid(),
		userName: 'Elizabeth Olsen',
		gender: 'Female',
		imageSrc: 'ElizabethOlsen.avif',
	},
	{
		id: newGuid(),
		userName: 'Scarlett Johansson',
		gender: 'Female',
		imageSrc: 'ScarlettJohansson.jpg',
	},
	{
		id: newGuid(),
		userName: 'Black Panther',
		gender: 'Male',
		imageSrc: 'BlackPanther.png',
	},
];
const GROUP_ID: string[] = [newGuid(), newGuid()];
const MESSAGES: Message[] = [
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[3].id,
		content: 'No arms and no legs',
		isFile: false,
		createDate: toSystemDate(NOW().subtract(48, 'hours')),
		lastUpdateDate: toSystemDate(NOW().subtract(48, 'hours')),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[3].id,
		content: 'Forever white hand',
		isFile: false,
		createDate: toSystemDate(addHours(new Date(), -47)),
		lastUpdateDate: toSystemDate(addHours(new Date(), -47)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[0].id,
		content: 'Gample life is so cruel',
		isFile: false,
		createDate: toSystemDate(addHours(new Date(), -23)),
		lastUpdateDate: toSystemDate(addHours(new Date(), -23)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[0].id,
		content: 'Make money like water, money still go',
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -45)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -45)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[1].id,
		content: 'No hand, white hand to zero',
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -30)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -30)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[2].id,
		content: "An adventure life, don't know tomorow",
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -29)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -29)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[2].id,
		content: 'Now I know the sorrow',
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -28)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -28)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[4].id,
		content: 'Sit in front the mirrow now I see',
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -27)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -27)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[4].id,
		content: "Somebody's there it's not me",
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -26)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -26)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [
			{
				userId: USERS[1].id,
				reactionDate: SYSTEM_NOW(),
				reaction: 'LOVE',
			},
			{
				userId: USERS[2].id,
				reactionDate: SYSTEM_NOW(),
				reaction: 'SAD',
			},
		],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[4].id,
		content: 'I am guilty, so then my body',
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -25)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -25)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[4].id,
		content: 'Has no friend and family',
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -24)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -24)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[0].id,
		content: "I am guilty, and now i'm so empty",
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -23)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -23)),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [
			{
				userId: USERS[1].id,
				reactionDate: SYSTEM_NOW(),
				reaction: 'LOVE',
			},
			{
				userId: USERS[2].id,
				reactionDate: SYSTEM_NOW(),
				reaction: 'SAD',
			},
		],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[0].id,
		content: 'Deleted message',
		isFile: false,
		createDate: toSystemDate(addMinutes(new Date(), -22)),
		lastUpdateDate: toSystemDate(addMinutes(new Date(), -22)),
		edited: false,
		deleted: true,
		relateId: undefined,
		logs: [
			{
				userId: USERS[1].id,
				reactionDate: SYSTEM_NOW(),
				reaction: 'LOVE',
			},
		],
	},
	{
		id: newGuid(),
		groupId: GROUP_ID[0],
		sender: USERS[0].id,
		content: 'Please stay away from lottery',
		isFile: false,
		createDate: SYSTEM_NOW(),
		lastUpdateDate: SYSTEM_NOW(),
		edited: false,
		deleted: false,
		relateId: undefined,
		logs: [
			{
				userId: USERS[1].id,
				reactionDate: SYSTEM_NOW(),
				reaction: 'LOVE',
			},
		],
	},
];

const CHAT_ROOMS: ChatRoom[] = [
	{
		id: GROUP_ID[0],
		name: 'Heroes',
		isGroup: true,
		members: USERS.map((e) => e.id),
		previewMsg: MESSAGES.at(-1),
	},
	{
		id: USERS[3].id,
		name: USERS[3].userName,
		isGroup: false,
		members: [],
		previewMsg: undefined,
	},
];

export { USERS, CHAT_ROOMS, MESSAGES, IMG_LIKE, IMG_HAHA, IMG_HEART, IMG_WOW, IMG_SAD, IMG_ANGRY };
